### ISSUE TITLE
Connection issues to MySQL

### ISSUE THREAD

**Issue by julianstephen** [brunocfnba/docker-airflow#1]
I was trying to get a simple flow running and ran into this issue. Seems like both `airflow-web` and `airflow-scheduler` are unable to connect the mysql server. I tried adding the mysql server as a service in the compose file, but that did not help either. 
```
Starting airflow-web ... 
Starting airflow-web ... done
Starting airflow-scheduler ... done
Attaching to airflow-mysql, airflow-web, airflow-scheduler
airflow-web  | Starting Airflow Webserver
airflow-mysql | 2018-04-30T18:06:22.609650Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
airflow-web  | Traceback (most recent call last):
airflow-web  |   File "/usr/local/bin/airflow", line 16, in <module>
airflow-web  |     from airflow import configuration
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/airflow/__init__.py", line 31, in <module>
airflow-web  |     from airflow import settings
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/airflow/settings.py", line 150, in <module>
airflow-web  |     configure_orm()
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/airflow/settings.py", line 136, in configure_orm
airflow-web  |     engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/__init__.py", line 391, in create_engine
airflow-web  |     return strategy.create(*args, **kwargs)
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 50, in create
airflow-web  |     u = url.make_url(name_or_url)
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 194, in make_url
airflow-web  |     return _parse_rfc1738_args(name_or_url)
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 240, in _parse_rfc1738_args
airflow-web  |     return URL(name, **components)
airflow-web  |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 60, in __init__
airflow-web  |     self.port = int(port)
airflow-web  | ValueError: invalid literal for int() with base 10: '<port>'
airflow-web exited with code 1
```
I do have the env_vars_web and env_vars_schedule with the correct port/host names
```
...
DB_HOST=airflow-mysql
DB_PORT=3306
```

Only change I tried was adding a mysql service to the same docker-compose-airflow.yml file
```
    mysql:
        image: mysql:latest
        container_name: airflow-mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=...
```

**Comment by julianstephen** [comment]
Fixed by changing the airflow.cfg file to
```
# The SqlAlchemy connection string to the metadata database.
# SqlAlchemy supports many different database engine, more information
# their website
<mysql_db_connection>
#sql_alchemy_conn = mysql://<user>:<password>@<hostname>:<port>/<database name>
```

Essentially the `init script` is doing a sed search replace for the string pattern `<mysql_db_connection>` and couldn't find it. 

Thanks
